name: Unit-test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup MySQL
      uses: shogo82148/actions-setup-mysql@v1
      with:
        user: test
        password: secret
        my-cnf: |
          binlog_format=row
          log-bin=mysql-bin
          server-id=1
    
    - name: Setup MongoDB
      uses: supercharge/mongodb-github-action@1.3.0

    - name: Test
      run: GOMODULE=1 go test --race ./...
